# -*- coding: utf-8 -*-
from . import test_config
from . import test_product_plan
from . import test_card
from . import test_installment_schedule
from . import test_payment
from . import test_card_confirm
from . import test_card_state
from . import test_routing
from . import test_audit_log
from . import test_route_batch
from . import test_transfer
from . import test_vendor_stock
from . import test_geolocation
from . import test_photos
from . import test_settlement
from . import test_supervision
from . import test_recovery
from . import test_problem_clients
from . import test_delivery_reversal
from . import test_sale_picking
from . import test_security
from . import test_agenda
from . import test_full_flow
from . import test_roles
