from . import test_account
from . import test_withdrawal
from . import test_installment
from . import test_payment
from . import test_withdrawal_state
from . import test_balance
from . import test_picking
from . import test_limit_and_cancel
from . import test_allocate_wizard
from . import test_statement
from . import test_dashboard_controller
