from . import res_company
from . import res_config_settings
from . import caw_account
from . import res_partner
from . import caw_withdrawal
from . import caw_installment
from . import caw_payment
from . import caw_allocation
from . import caw_withdrawal_line
